### ISSUE TITLE
Load failed. Error: System.Exection: Invaid scene file header magic at RSDKv5.Scene..ctor(Reader reader)

### ISSUE THREAD

**Issue by johnlemon647** [OtherworldBob/ManiacEditor#32]
Maniac Editor have error will not let enter level editor. I need Help
Load failed. Error: System.Exection: Invaid scene file header magic at RSDKv5.Scene..ctor(Reader reader)
at ManiacEditor. EditorScene..ctor(StringFilename) at ManiacEditor.OpenScene(). Because error My Dust Hill Mods have black screen and crash when loaded on Sonic Mania.

**Comment by CarJem** [comment]
There's a chance your issue may stem from issue #3 or you managed to corrupt your file's header.
