### ISSUE TITLE
Stages won't load up.

### ISSUE THREAD

**Issue by Ezoiar** [OtherworldBob/ManiacEditor#37]
It won't load up to edit, and i'm pretty sure it is the gameconfig.

but i know an fix if you have it also (for users)
**it's annoying fix.**
First of all, open up the other mod or mania plus folder.
open data folder, then press browse, go back the your mod folder that the stages won't load up, go to stages, select stages, press the SceneX.bin, then you're done.

for the devs who made this program, please, please fix it, thank you.

**Comment by XanderBeck** [comment]
yea.

**Comment by XanderBeck** [comment]
and this is the error text i get
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at RSDKv5.GameConfig.ConfigurableMemoryEntry..ctor(Reader reader)
   at RSDKv5.GameConfig.Read(Reader reader)
   at RSDKv5.GameConfig..ctor(String filename)
   at ManiacEditor.Editor.SetGameConfig()
   at ManiacEditor.Editor.load()
   at ManiacEditor.Editor.Open_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ManiacEditor
    Assembly Version: 0.2.25.81
    Win32 Version: 0.2.25.81
    CodeBase: file:///E:/ManiacEditor-Beta-Positivity-v0.2.25.81/ManiacEditor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
RSDKv5
    Assembly Version: 0.2.25.81
    Win32 Version: 0.2.25.81
    CodeBase: file:///E:/ManiacEditor-Beta-Positivity-v0.2.25.81/RSDKv5.DLL
----------------------------------------
INIFileParser
    Assembly Version: 2.5.2.0
    Win32 Version: 2.5.2
    CodeBase: file:///E:/ManiacEditor-Beta-Positivity-v0.2.25.81/INIFileParser.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2563.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
SharpDX.Direct3D9
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///E:/ManiacEditor-Beta-Positivity-v0.2.25.81/SharpDX.Direct3D9.DLL
----------------------------------------
SharpDX
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///E:/ManiacEditor-Beta-Positivity-v0.2.25.81/SharpDX.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SharpDX.Desktop
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///E:/ManiacEditor-Beta-Positivity-v0.2.25.81/SharpDX.Desktop.DLL
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///E:/ManiacEditor-Beta-Positivity-v0.2.25.81/SharpDX.Mathematics.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
